version: "3"

services:
  postgres:
    container_name: "alonebot_postgres"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=alonebot
      - POSTGRES_PASSWORD=alonebot
      - POSTGRES_DATABASE=alonebot
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alonebot"]
      interval: 2s
      timeout: 1s
      retries: 5

  bot:
    container_name: "alonebot"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/main:ro
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      JISHAKU_HIDE: "True"
      JISHAKU_RETAIN: "True"
      JISHAKU_NO_UNDERSCORE: "True"
      JISHAKU_FORCE_PAGINATOR: "True"
      JISHAKU_NO_DM_TRACEBACK: "True"